import { UAParser } from 'ua-parser-js';
import { Injectable, NestMiddleware } from '@nestjs/common';
import type { Request, Response, NextFunction } from 'express';

/**
 * Parsed device metadata attached to every request by DeviceInfoMiddleware.
 * Controllers/services read this from `req.deviceMeta`.
 */
export interface RequestDeviceMeta {
  userAgent: string | undefined;
  ipAddress: string | undefined;
  deviceId: string | undefined;
  deviceName: string;
  deviceType: string;
}

/**
 * Middleware that extracts and normalizes device information from request headers.
 *
 * Headers consumed:
 * - `User-Agent`     → parsed via ua-parser-js for browser, OS, device type
 * - `X-Device-Id`    → persistent device identifier generated by the client
 * - `X-Forwarded-For` / socket.remoteAddress → client IP
 */
@Injectable()
export class DeviceInfoMiddleware implements NestMiddleware {
  use(req: Request, _res: Response, next: NextFunction) {
    const userAgent = req.headers['user-agent'];
    const deviceId = req.headers['x-device-id'] as string | undefined;
    const ipAddress =
      (req.headers['x-forwarded-for'] as string)?.split(',')[0]?.trim() ??
      req.socket?.remoteAddress ??
      undefined;

    const parsed = DeviceInfoMiddleware.parseUserAgent(userAgent);

    (req as any).deviceMeta = {
      userAgent,
      ipAddress,
      deviceId: deviceId || undefined,
      deviceName: parsed.deviceName,
      deviceType: parsed.deviceType,
    } satisfies RequestDeviceMeta;

    next();
  }

  /**
   * Parse a User-Agent string into structured browser, OS, and device info
   * using ua-parser-js for accurate cross-platform detection.
   */
  static parseUserAgent(userAgent?: string): {
    deviceName: string;
    deviceType: string;
  } {
    if (!userAgent) {
      return {
        deviceName: 'Unknown',
        deviceType: 'other',
      };
    }

    const parser = new UAParser(userAgent);
    const browserResult = parser.getBrowser();
    const osResult = parser.getOS();
    const deviceResult = parser.getDevice();

    // ua-parser-js device.type: console, mobile, tablet, smarttv, wearable, embedded, undefined (= desktop)
    let deviceType = 'desktop';
    if (deviceResult.type) {
      deviceType =
        deviceResult.type === 'mobile' || deviceResult.type === 'tablet'
          ? deviceResult.type
          : 'other';
    }

    // Human-readable: "Chrome 125 on Windows 11"
    const browserName = browserResult.name ?? 'Unknown Browser';
    const osName = osResult.name ?? 'Unknown OS';
    const deviceName = `${browserName} on ${osName}`;

    return { deviceName, deviceType };
  }
}
