import {
  Body,
  Controller,
  Delete,
  Get,
  HttpCode,
  HttpStatus,
  Param,
  Post,
  Req,
  Res,
  UseGuards,
} from '@nestjs/common';
import {
  ApiTags,
  ApiOperation,
  ApiResponse,
  ApiBearerAuth,
  ApiParam,
  ApiHeader,
} from '@nestjs/swagger';
import { ConfigService } from '@nestjs/config';
import type { Request, Response } from 'express';
import { AuthService, AuthTokens } from './auth.service';
import type { Configs } from '@lib/config/config.interface';
import type { SessionInfo } from '@modules/token/token.service';
import {
  LoginDto,
  RegisterDto,
  VerifyOtpDto,
  ChangePasswordDto,
  ForgotPasswordDto,
  ResetPasswordDto,
  AuthTokensResponse,
  LoginOtpResponse,
  MessageResponse,
  SessionInfoResponse,
} from './dto';
import { Public } from '@common/decorators/public.decorator';
import { GoogleAuthGuard } from '@common/guards/google-auth.guard';
import { JwtRefreshGuard } from '@common/guards/jwt-refresh.guard';
import { DeviceMeta } from '@common/decorators/device-meta.decorator';
import { CustomThrottle } from '@common/decorators/throttle.decorator';
import { CurrentUser } from '@common/decorators/current-user.decorator';
import { BearerToken } from '@common/decorators/bearer-token.decorator';
import { ResponseMessage } from '@common/decorators/response-message.decorator';
import type { RequestDeviceMeta } from '@common/middleware/device-info.middleware';

@ApiTags('Auth')
@ApiHeader({
  name: 'X-Device-Id',
  description:
    'Persistent device UUID (generated by client, stored in localStorage)',
  required: false,
})
@Controller('auth')
export class AuthController {
  constructor(
    private readonly authService: AuthService,
    private readonly configService: ConfigService<Configs, true>,
  ) {}

  // ── Register ───────────────────────────────────────────────────────────────

  @Public()
  @Post('register')
  @CustomThrottle(5, 60)
  @ResponseMessage('User registered successfully')
  @ApiOperation({ summary: 'Register a new user' })
  @ApiResponse({
    status: 201,
    description: 'User registered successfully',
    type: AuthTokensResponse,
  })
  @ApiResponse({ status: 409, description: 'User already exists' })
  @ApiResponse({ status: 429, description: 'Too many requests' })
  async register(
    @Body() dto: RegisterDto,
    @DeviceMeta() meta: RequestDeviceMeta,
  ): Promise<AuthTokens> {
    return this.authService.register(dto, meta);
  }

  // ── Login Step 1: Credentials → OTP email ─────────────────────────────────

  @Public()
  @Post('login')
  @HttpCode(HttpStatus.OK)
  @CustomThrottle(10, 60)
  @ResponseMessage('OTP sent to your email for verification')
  @ApiOperation({
    summary: 'Login — validates credentials and sends OTP to email',
  })
  @ApiResponse({
    status: 200,
    description: 'OTP sent to email for verification',
    type: LoginOtpResponse,
  })
  @ApiResponse({ status: 401, description: 'Invalid credentials' })
  @ApiResponse({ status: 429, description: 'Too many requests' })
  async login(
    @Body() dto: LoginDto,
  ): Promise<{ message: string; requiresOtp: boolean }> {
    return this.authService.login(dto);
  }

  // ── Login Step 2: Verify OTP → Tokens ─────────────────────────────────────

  @Public()
  @Post('verify-login-otp')
  @HttpCode(HttpStatus.OK)
  @CustomThrottle(3, 60)
  @ResponseMessage('Login successful')
  @ApiOperation({
    summary: 'Verify login OTP and receive access + refresh tokens',
  })
  @ApiResponse({
    status: 200,
    description: 'Login successful, tokens returned',
    type: AuthTokensResponse,
  })
  @ApiResponse({ status: 400, description: 'Invalid or expired OTP' })
  @ApiResponse({ status: 429, description: 'Too many requests' })
  async verifyLoginOtp(
    @Body() dto: VerifyOtpDto,
    @DeviceMeta() meta: RequestDeviceMeta,
  ): Promise<AuthTokens> {
    return this.authService.verifyLoginOtp(dto, meta);
  }

  // ── Refresh ────────────────────────────────────────────────────────────────

  @Public()
  @UseGuards(JwtRefreshGuard)
  @Post('refresh')
  @HttpCode(HttpStatus.OK)
  @ApiBearerAuth()
  @ResponseMessage('Tokens refreshed successfully')
  @ApiOperation({
    summary:
      'Rotate refresh token — old session is revoked, new session issued',
  })
  @ApiResponse({
    status: 200,
    description: 'Tokens refreshed successfully',
    type: AuthTokensResponse,
  })
  @ApiResponse({ status: 401, description: 'Invalid or expired refresh token' })
  async refresh(
    @CurrentUser('id') userId: number,
    @CurrentUser('sessionIdx') sessionIdx: string,
    @CurrentUser('refreshToken') refreshToken: string,
    @DeviceMeta() meta: RequestDeviceMeta,
  ): Promise<AuthTokens> {
    return this.authService.refreshTokens(
      userId,
      sessionIdx,
      refreshToken,
      meta,
    );
  }

  // ── Logout current device ─────────────────────────────────────────────────

  @Post('logout')
  @HttpCode(HttpStatus.OK)
  @ApiBearerAuth()
  @ResponseMessage('Logged out successfully')
  @ApiOperation({
    summary: 'Logout current device — revokes this session only',
  })
  @ApiResponse({
    status: 200,
    description: 'Logged out successfully',
    type: MessageResponse,
  })
  @ApiResponse({ status: 401, description: 'Unauthorized' })
  async logout(
    @CurrentUser('id') userId: number,
    @CurrentUser('sessionIdx') sessionIdx: string,
    @BearerToken() accessToken: string,
  ): Promise<{ message: string }> {
    await this.authService.logout(userId, sessionIdx, accessToken);
    return { message: 'Logged out successfully' };
  }

  // ── Sessions: list ────────────────────────────────────────────────────────

  @Get('sessions')
  @ApiBearerAuth()
  @ResponseMessage('Active sessions retrieved')
  @ApiOperation({ summary: 'List all active sessions for the current user' })
  @ApiResponse({
    status: 200,
    description: 'Active sessions list',
    type: [SessionInfoResponse],
  })
  async getSessions(
    @CurrentUser('id') userId: number,
    @CurrentUser('sessionIdx') currentSessionIdx: string,
  ): Promise<(SessionInfo & { isCurrent: boolean })[]> {
    const sessions = await this.authService.getActiveSessions(userId);
    return sessions.map((s) => ({
      ...s,
      isCurrent: s.sessionIdx === currentSessionIdx,
    }));
  }

  // ── Sessions: logout all devices ─────────────────────────────────────────

  @Delete('sessions')
  @HttpCode(HttpStatus.OK)
  @ApiBearerAuth()
  @ResponseMessage('All sessions revoked')
  @ApiOperation({
    summary: 'Logout all devices — revokes every active session',
  })
  @ApiResponse({
    status: 200,
    description: 'All sessions revoked',
    type: MessageResponse,
  })
  async logoutAllDevices(
    @CurrentUser('id') userId: number,
    @BearerToken() accessToken: string,
  ): Promise<{ message: string }> {
    await this.authService.logoutAllDevices(userId, accessToken);
    return { message: 'All devices logged out successfully' };
  }

  // ── Sessions: logout specific device ─────────────────────────────────────

  @Delete('sessions/:sessionIdx')
  @HttpCode(HttpStatus.OK)
  @ApiBearerAuth()
  @ResponseMessage('Session revoked')
  @ApiOperation({ summary: 'Logout a specific device by session ID' })
  @ApiParam({
    name: 'sessionIdx',
    description: 'Session UUID returned in AuthTokens.sessionIdx',
  })
  @ApiResponse({
    status: 200,
    description: 'Session revoked',
    type: MessageResponse,
  })
  @ApiResponse({ status: 404, description: 'Session not found' })
  async revokeSession(
    @CurrentUser('id') userId: number,
    @Param('sessionIdx') sessionIdx: string,
  ): Promise<{ message: string }> {
    return this.authService.revokeSession(userId, sessionIdx);
  }

  // ── Change Password ───────────────────────────────────────────────────────

  @Post('change-password')
  @HttpCode(HttpStatus.OK)
  @ApiBearerAuth()
  @ResponseMessage('Password changed successfully')
  @ApiOperation({ summary: 'Change password for authenticated user' })
  @ApiResponse({
    status: 200,
    description: 'Password changed successfully',
    type: MessageResponse,
  })
  @ApiResponse({
    status: 400,
    description: 'Cannot change password for OAuth accounts',
  })
  @ApiResponse({ status: 401, description: 'Current password is incorrect' })
  async changePassword(
    @CurrentUser('id') userId: number,
    @Body() dto: ChangePasswordDto,
    @BearerToken() accessToken: string,
  ): Promise<{ message: string }> {
    return this.authService.changePassword(userId, dto, accessToken);
  }

  // ── Forgot Password ──────────────────────────────────────────────────────

  @Public()
  @Post('forgot-password')
  @HttpCode(HttpStatus.OK)
  @CustomThrottle(3, 60)
  @ResponseMessage('Password reset code sent to your email')
  @ApiOperation({ summary: 'Request password reset OTP via email' })
  @ApiResponse({
    status: 200,
    description: 'Reset code sent if account exists',
    type: MessageResponse,
  })
  @ApiResponse({ status: 429, description: 'Too many requests' })
  async forgotPassword(
    @Body() dto: ForgotPasswordDto,
  ): Promise<{ message: string }> {
    return this.authService.forgotPassword(dto);
  }

  // ── Reset Password ────────────────────────────────────────────────────────

  @Public()
  @Post('reset-password')
  @HttpCode(HttpStatus.OK)
  @CustomThrottle(3, 60)
  @ResponseMessage('Password reset successfully')
  @ApiOperation({ summary: 'Reset password with OTP code' })
  @ApiResponse({
    status: 200,
    description: 'Password reset successfully',
    type: MessageResponse,
  })
  @ApiResponse({ status: 400, description: 'Invalid OTP or email' })
  @ApiResponse({ status: 429, description: 'Too many requests' })
  async resetPassword(
    @Body() dto: ResetPasswordDto,
  ): Promise<{ message: string }> {
    return this.authService.resetPassword(dto);
  }

  // ── Google OAuth ──────────────────────────────────────────────────────────

  @Public()
  @Get('google')
  @UseGuards(GoogleAuthGuard)
  @ApiOperation({ summary: 'Initiate Google OAuth2 login' })
  @ApiResponse({ status: 302, description: 'Redirects to Google login' })
  googleAuth() {
    // Guard handles the redirect
  }

  @Public()
  @Get('google/callback')
  @UseGuards(GoogleAuthGuard)
  @ApiOperation({
    summary: 'Google OAuth2 callback — redirects to frontend with tokens',
  })
  @ApiResponse({
    status: 302,
    description: 'Redirects to CLIENT_URL/auth/callback with tokens',
  })
  async googleCallback(
    @Req() req: Request,
    @Res() res: Response,
  ): Promise<void> {
    const meta: RequestDeviceMeta = (req as any).deviceMeta;
    const tokens = await this.authService.googleLogin(req.user as any, meta);
    const { clientUrl } = this.configService.getOrThrow('app', { infer: true });
    const redirectUrl = new URL('/auth/callback', clientUrl);
    redirectUrl.searchParams.set('accessToken', tokens.accessToken);
    redirectUrl.searchParams.set('refreshToken', tokens.refreshToken);
    redirectUrl.searchParams.set('sessionIdx', tokens.sessionIdx);
    res.redirect(redirectUrl.toString());
  }
}
